### ISSUE TITLE
beta version

### ISSUE THREAD

**Issue by mattiaerre** [prettier-solidity/prettier-plugin-solidity#10]
# Description

I'm adding a todo list of things we should be doing prior the 1st publishing on npm of this plugin; feel free to comment on this issue if I've missed something

## Todos

- [x] integrate @federicobond 's `genericPrint` function

- [x]  add additional examples (more complex contracts)

- [x] update README.md; check [official-plugins](https://prettier.io/docs/en/plugins.html#official-plugins) and [community-plugins](https://prettier.io/docs/en/plugins.html#community-plugins) for examples

**Comment by mattiaerre** [comment]
![Alt Text](https://media.giphy.com/media/12XYXZMDDqHChy/giphy.gif)

// cc @federicobond

**Comment by mattiaerre** [comment]
there is an open PR that contains @federicobond 's printer function although we need to:

- [ ] preserve comments

**Comment by mattiaerre** [comment]
@federicobond I will proceed and merge #21 if you don't mind; also I'd love to make sure we can preserve comments; is that alright?

**Comment by fvictorio** [comment]
HI @mattiaerre, this plugin is a great idea. I see that there's still a lot of work pending. I'd like to help if you want!

I'd suggest that you merge #21, which seems to work fine, and to open issues for each pending thing  (one for preserving comments, one for separating functions with empty lines, etc.). That way, potential contributors will be able to help.

I also thing that each contribution should come with at least one new test case, or a modification of a current fixture. The nice thing about this is that is very testable, so people should be able to contribute with confidence.

**Comment by mattiaerre** [comment]
hi @fvictorio thanks so much for your message. yes, there is still a lot of work pending and #21 is still not merged. but as per my last comment, I guess it's about time. of course it'd be nice to get some help so let's do this: I'll merge and we can start adding new functionalities as per your suggestion. I'm totally down w/ tests and everything as this repo has got all the automation needed to support that workflow.

// cc @federicobond

**Comment by mattiaerre** [comment]
#21 has been merged; also there is a [gitter](https://gitter.im/prettier-solidity/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) channel for you to join

// cc @fvictorio

**Comment by fvictorio** [comment]
What do we need to do to close this?

**Comment by mattiaerre** [comment]
we've got plenty of examples now 👍
